/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "FreeRTOS.h"
#include "task.h"

#include "LED_interface.h"
#include "STK_interface.h"
#include "RCC_interface.h"
#include "DIO_interface.h"

TaskHandle_t	xRedLEDTaskHandle;
TaskHandle_t	xGreenLEDTaskHandle;

void	vRedLEDTask( void * pvParameters );
void	vGreenLEDTask( void * pvParameters );

int main(void)
{
	RCC_voidSysClkInt();
	RCC_voidEnablePerClk(RCC_APB2, 2);
	LED_init(PORTA, PIN0);
	LED_init(PORTA, PIN1);
	/*Toggle pin*/
			LED_toggle(PORTA, PIN1);
			/*Periodicity*/
			STK_voidSetBusyWait(500);
	STK_voidInit();
	xTaskCreate(vRedLEDTask, "Red LED Task", 128, NULL, 1, &xRedLEDTaskHandle);
	xTaskCreate(vGreenLEDTask, "Green LED Task", 128, NULL, 1, &xGreenLEDTaskHandle);

    // Start the real time scheduler.
    vTaskStartScheduler();

    // Will not get here unless there is insufficient RAM.
	/* Loop forever */

	for(;;);
}


void	vRedLEDTask( void * pvParameters )
{
	for(;;)
	{
		/*Toggle pin*/
		LED_toggle(PORTA, PIN0);
		/*Periodicity*/
		vTaskDelay(700);
//		STK_busywait(500);
	}
}
void	vGreenLEDTask( void * pvParameters )
{
	for(;;)
	{
		/*Toggle pin*/
				LED_toggle(PORTA, PIN1);
				/*Periodicity*/
				vTaskDelay(500);
				//vTaskDelete(xRedLEDTaskHandle);
		//		STK_busywait(500);
	}
}
