#include	"stdTypes.h"
#include	"Bit_Math.h"

#include	"RCC_interface.h"
#include	"RCC_private.h"
#include	"RCC_config.h"

void		RCC_voidSysClkInt(void)
{
#if RCC_SYS_CLK == RCC_HSE
	RCC_CR_HSE_ON;
	RCC_CFGR_SW_HSE1;
	RCC_CFGR_SW_HSE2;
	while (RCC_CR_HSE_ON_RDY == 0 );
#elif RCC_SYS_CLK == RCC_HSI
	RCC_CR_HSI_ON;
	RCC_CFGR_SW_HSI1;
	RCC_CFGR_SW_HSI2;
	while (RCC_CR_HSI_ON_RDY==0);
#elif RCC_SYS_CLK == RCC_PLL
	#if RCC_CLOCKTYPE == RCC_HSE
		SET_BIT(RCC_CFGR, 16);
	#elif RCC_CLOCKTYPE == RCC_HSI
		CLR_BIT(RCC_CFGR, 16);//HSI/2
	#endif
	//PLL PRESCALER
	#if PLL_PRE == X1
			SET_BIT(RCC_CFGR, 17);//PLL_XTPRE
			CLR_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X2 
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			CLR_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X3
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X4
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			CLR_BIT(RCC_CFGR, 18);//PLL_MUL0
			SET_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X5
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			SET_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X6
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			CLR_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			SET_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X7
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			SET_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X8
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			CLR_BIT(RCC_CFGR, 18);//PLL_MUL0
			SET_BIT(RCC_CFGR, 19);//PLL_MUL1
			SET_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X9
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			SET_BIT(RCC_CFGR, 19);//PLL_MUL1
			SET_BIT(RCC_CFGR, 20);//PLL_MUL2
			CLR_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X10
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			CLR_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			SET_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X11
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			SET_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X12
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			SET_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X13
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			SET_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X14
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			SET_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X15
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			SET_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X16_1
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			SET_BIT(RCC_CFGR, 21);//PLL_MUL3
	#elif PLL_PRE == X16_2
			CLR_BIT(RCC_CFGR, 17);//PLL_XTPRE
			SET_BIT(RCC_CFGR, 18);//PLL_MUL0
			CLR_BIT(RCC_CFGR, 19);//PLL_MUL1
			CLR_BIT(RCC_CFGR, 20);//PLL_MUL2
			SET_BIT(RCC_CFGR, 21);//PLL_MUL3
	#else
		#error "Error wrong choose PLL CLK "
	#endif
	//ENABLE PLL
	RCC_CR_PLL_ON;
	while (!RCC_CR_PLL_ON_RDY);
	RCC_CFGR_SW_PLL1;
	RCC_CFGR_SW_PLL2;
	WHILE(!(RCC_CFGR_SWS_PLL));
#else
		#error "Error wrong choice for CLK system"
#endif
#if     MCO == NO_CLK
	CLR_BIT(RCC_CFGR,24) ;
	CLR_BIT(RCC_CFGR,25) ;
	CLR_BIT(RCC_CFGR,26) ;
#elif 	MCO == SYS_CLK
	CLR_BIT(RCC_CFGR,24) ;
	CLR_BIT(RCC_CFGR,25) ;
	SET_BIT(RCC_CFGR,26) ;
#elif 	MCO == HSI_CLK
	SET_BIT(RCC_CFGR,24) ;
	CLR_BIT(RCC_CFGR,25) ;
	SET_BIT(RCC_CFGR,26) ;
#elif 	MCO == HSE_CLK
	CLR_BIT(RCC_CFGR,24) ;
	SET_BIT(RCC_CFGR,25) ;
	SET_BIT(RCC_CFGR,26) ;
#elif 	MCO == PLL_CLK_DEV2
	SET_BIT(RCC_CFGR,24) ;
	SET_BIT(RCC_CFGR,25) ;
	SET_BIT(RCC_CFGR,26) ;
#else
	#error "wrong choose MCO "
#endif 


		
}
void		RCC_voidEnablePerClk(u8 BusId , u8 PerId)
{
	/*		Range Check							*/
	if(PerId < 32)
	{
		switch(BusId)
		{
			case	RCC_AHB		:	SET_BIT(RCC_AHBENR,PerId) ;	break;
			case	RCC_APB1	:	SET_BIT(RCC_APB1ENR,PerId);	break;
			case	RCC_APB2	:	SET_BIT(RCC_APB2ENR,PerId);	break;
		}
		
	}
	else{	/*	Return Error "Out Of The Range"		*/	}
	
}
void		RCC_voidDisablePerClk(u8 BusId , u8 PerId)
{
	/*		Range Check							*/
	if(PerId < 32)
	{
		switch(BusId)
		{
			case	RCC_AHB		:	CLR_BIT(RCC_AHBENR,PerId) ;	break;
			case	RCC_APB1	:	CLR_BIT(RCC_APB1ENR,PerId);	break;
			case	RCC_APB2	:	CLR_BIT(RCC_APB2ENR,PerId);	break;
		}
		
	}
	else{	/*	Return Error "Out Of The Range"		*/	}	
}
